name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install bundler -y

      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        run: yarn

      - run: yarn install cypress

      - name: Percy Test
        uses: percy/exec-action@v0.1.1
        with:
          command: "cypress run"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
